[Unit]
Requires=eidetic-labwc.service
After=eidetic-labwc.service
PartOf=eidetic-graphical-session.target

[Service]
Environment=XDG_SESSION_TYPE=wayland
Environment=XDG_CURRENT_DESKTOP=labwc
Environment=XDG_SESSION_DESKTOP=labwc
ExecStart=
ExecStart=/usr/libexec/eidetic-player-graphical-launch
